[build]
  publish = "public"
  functions = "func"
  command = "node --unhandled-rejections=strict build.js"

[build.environment]
  AWS_LAMBDA_JS_RUNTIME = "nodejs14.x"

[build.processing]
  css = { bundle = true, minify = true }
  js = { bundle = true, minify = true }
  html = { pretty_urls = true }
  images = { compress = true }

[functions]
  node_bundler = "esbuild"

[template.environment]
  DISCORD_CLIENT_ID = "815218789150097408"
  DISCORD_CLIENT_SECRET = "C9Z6MHIaQ6hoiL-wSMavJ67u-FgUNhCH"
  DISCORD_BOT_TOKEN = ""
  GUILD_ID = "959516864218808411"
  APPEALS_CHANNEL = "971787678364360714"
  JWT_SECRET = "dsahgfuorheg"
